/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antee_number24_Number24Calculator */

#ifndef _Included_com_antee_number24_Number24Calculator
#define _Included_com_antee_number24_Number24Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antee_number24_Number24Calculator
 * Method:    calculate
 * Signature: (IIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_antee_number24_Number24Calculator_calculate
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
